python3 ./src/main.py \
    --population-size 50 \
    --crossover-rate 0.6 \
    --mutation-rate 0.4 \
    --max-iterations 20000 \
    --elitism-rate 0.1 \
    --selection-pressure 1.5 \
    --stagnation-limit 100 \
    --seed 0 \
    test.txt < example_instances/dog_7.txt 