python3 ./src/main.py \
    --population-size 100 \
    --crossover-rate 0.8 \
    --mutation-rate 0.3 \
    --elitism-rate 0.2 \
    --selection-pressure 1.5 \
    --time-limit 1800 \
    --seed 0 \
    test.txt < example_instances/dog_7.txt 